{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.wsl.bareMounts;

  # Generate PowerShell script content for Windows-side execution
  generateMountScript = mounts: ''
    #Requires -Version 5.1
    #Requires -RunAsAdministrator

    # WSL Bare Mount Script
    # Generated by NixOS-WSL
    # This script must be executed with Administrator privileges before WSL starts

    $ErrorActionPreference = "Stop"

    function Test-DiskMounted {
        param([string]$DiskUuid)

        try {
            $output = & wsl --list --running 2>$null
            if ($LASTEXITCODE -eq 0 -and $output) {
                # WSL is running, check if disk is mounted
                $mountOutput = & wsl --exec lsblk -o UUID 2>$null | Select-String -Pattern $DiskUuid -Quiet
                return $mountOutput
            }
            return $false
        } catch {
            return $false
        }
    }

    function Mount-BareDisk {
        param(
            [string]$DiskUuid,
            [string]$Description
        )

        Write-Host "Checking disk: $Description (UUID: $DiskUuid)"

        if (Test-DiskMounted -DiskUuid $DiskUuid) {
            Write-Host "  [SKIP] Already mounted" -ForegroundColor Green
            return $true
        }

        try {
            Write-Host "  [MOUNT] Attempting to mount..." -ForegroundColor Yellow

            # Find the disk by UUID
            $disk = Get-Disk | Where-Object {
                $_.UniqueId -like "*$DiskUuid*" -or
                $_.SerialNumber -eq $DiskUuid
            }

            if (-not $disk) {
                Write-Host "  [ERROR] Disk not found in Windows" -ForegroundColor Red
                return $false
            }

            # Perform the bare mount
            & wsl --mount \\.\PHYSICALDRIVE$($disk.Number) --bare

            if ($LASTEXITCODE -eq 0) {
                Write-Host "  [SUCCESS] Mounted successfully" -ForegroundColor Green
                return $true
            } else {
                Write-Host "  [ERROR] Mount command failed with exit code $LASTEXITCODE" -ForegroundColor Red
                return $false
            }
        } catch {
            Write-Host "  [ERROR] $($_.Exception.Message)" -ForegroundColor Red
            return $false
        }
    }

    Write-Host "`n=== WSL Bare Mount Script Starting ===" -ForegroundColor Cyan
    Write-Host "Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    Write-Host "Machine: $env:COMPUTERNAME"

    $failedMounts = @()

    ${concatMapStringsSep "\n    " (mount: ''
      if (-not (Mount-BareDisk -DiskUuid "${mount.diskUuid}" -Description "${mount.mountPoint}")) {
          $failedMounts += "${mount.diskUuid}"
      }
    '') mounts}

    Write-Host "`n=== Summary ===" -ForegroundColor Cyan
    if ($failedMounts.Count -eq 0) {
        Write-Host "All disks mounted successfully" -ForegroundColor Green
        exit 0
    } else {
        Write-Host "Failed to mount $($failedMounts.Count) disk(s):" -ForegroundColor Red
        $failedMounts | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
        exit 1
    }
  '';

  # Generate Task Scheduler XML for automatic mounting
  generateTaskXml = ''
    <?xml version="1.0" encoding="UTF-16"?>
    <Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
      <RegistrationInfo>
        <Date>2025-01-01T00:00:00</Date>
        <Author>NixOS-WSL</Author>
        <Description>Automatically mount bare disks for WSL before WSL starts</Description>
        <URI>\WSL\BareMountDisks</URI>
      </RegistrationInfo>
      <Triggers>
        <LogonTrigger>
          <Enabled>true</Enabled>
        </LogonTrigger>
      </Triggers>
      <Principals>
        <Principal id="Author">
          <UserId>S-1-5-18</UserId>
          <RunLevel>HighestAvailable</RunLevel>
        </Principal>
      </Principals>
      <Settings>
        <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
        <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
        <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
        <AllowHardTerminate>true</AllowHardTerminate>
        <StartWhenAvailable>true</StartWhenAvailable>
        <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
        <IdleSettings>
          <StopOnIdleEnd>false</StopOnIdleEnd>
          <RestartOnIdle>false</RestartOnIdle>
        </IdleSettings>
        <AllowStartOnDemand>true</AllowStartOnDemand>
        <Enabled>true</Enabled>
        <Hidden>false</Hidden>
        <RunOnlyIfIdle>false</RunOnlyIfIdle>
        <WakeToRun>false</WakeToRun>
        <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>
        <Priority>7</Priority>
      </Settings>
      <Actions Context="Author">
        <Exec>
          <Command>powershell.exe</Command>
          <Arguments>-ExecutionPolicy Bypass -WindowStyle Hidden -File "%USERPROFILE%\.nixos-wsl\bare-mount.ps1"</Arguments>
        </Exec>
      </Actions>
    </Task>
  '';

  # Generate installer script for Task Scheduler
  generateInstallerScript = ''
    #Requires -Version 5.1
    #Requires -RunAsAdministrator

    # WSL Bare Mount Task Installer
    # This script installs a scheduled task to automatically mount bare disks

    $ErrorActionPreference = "Stop"

    Write-Host "WSL Bare Mount Task Installer" -ForegroundColor Cyan
    Write-Host "================================" -ForegroundColor Cyan

    # Define paths
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $mountScript = Join-Path $scriptDir "bare-mount.ps1"
    $taskXml = Join-Path $scriptDir "bare-mount-task.xml"
    $taskName = "WSL-BareMountDisks"

    # Check if mount script exists
    if (-not (Test-Path $mountScript)) {
        Write-Host "ERROR: Mount script not found at: $mountScript" -ForegroundColor Red
        exit 1
    }

    # Check if task XML exists
    if (-not (Test-Path $taskXml)) {
        Write-Host "ERROR: Task XML not found at: $taskXml" -ForegroundColor Red
        exit 1
    }

    # Check if task already exists
    $existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($existingTask) {
        Write-Host "Task already exists. Updating..." -ForegroundColor Yellow
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    }

    # Register the task
    try {
        Register-ScheduledTask -TaskName $taskName -Xml (Get-Content $taskXml | Out-String) -Force
        Write-Host "SUCCESS: Task '$taskName' installed successfully!" -ForegroundColor Green
        
        # Test run the task
        Write-Host "`nTesting the task by running it once..." -ForegroundColor Yellow
        Start-ScheduledTask -TaskName $taskName
        
        Start-Sleep -Seconds 3
        
        $taskInfo = Get-ScheduledTaskInfo -TaskName $taskName
        if ($taskInfo.LastTaskResult -eq 0) {
            Write-Host "SUCCESS: Test run completed successfully!" -ForegroundColor Green
        } else {
            Write-Host "WARNING: Test run completed with exit code: $($taskInfo.LastTaskResult)" -ForegroundColor Yellow
        }
        
        Write-Host "`nThe task is now configured to run at user logon." -ForegroundColor Green
        Write-Host "You can manage it through Task Scheduler (taskschd.msc)" -ForegroundColor Cyan
    } catch {
        Write-Host "ERROR: Failed to register task: $_" -ForegroundColor Red
        exit 1
    }
  '';

  # Generate systemd service for validation
  validationService = {
    description = "Validate WSL Bare Mounts";
    after = [ "multi-user.target" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      set -euo pipefail

      echo "Validating WSL bare mounts..."
      MISSING_DEVICES=""

      ${concatMapStringsSep "\n" (mount: ''
        if [ ! -e "/dev/disk/by-uuid/${mount.diskUuid}" ]; then
          echo "ERROR: Block device for ${mount.mountPoint} (UUID: ${mount.diskUuid}) not found!"
          echo "  Please ensure the Windows-side mount script has been executed."
          MISSING_DEVICES="$MISSING_DEVICES ${mount.diskUuid}"
        else
          echo "OK: Found block device for ${mount.mountPoint} (UUID: ${mount.diskUuid})"
        fi
      '') cfg.mounts}

      if [ -n "$MISSING_DEVICES" ]; then
        echo ""
        echo "CRITICAL: Missing block devices detected!"
        echo "The following disks must be bare-mounted from Windows before starting WSL:"
        echo "$MISSING_DEVICES"
        echo ""
        echo "To fix this issue:"
        echo "1. Exit WSL completely (wsl --shutdown)"
        echo "2. Run the mount script as Administrator:"
        echo "   %USERPROFILE%\\.nixos-wsl\\bare-mount.ps1"
        echo "3. Restart WSL"
        echo ""
        echo "For automatic mounting, integrate this script into your WSL startup process."
        exit 1
      fi

      echo "All configured bare mounts are available."
    '';
  };

in {
  options.wsl.bareMounts = {
    enable = mkEnableOption "WSL bare disk mounting support";

    mounts = mkOption {
      type = types.listOf (types.submodule {
        options = {
          diskUuid = mkOption {
            type = types.str;
            description = ''
              UUID of the Windows physical disk to bare mount.
              This should match the UUID visible in Windows Disk Management.
            '';
            example = "abc12345-def6-7890-1234-567890abcdef";
          };

          mountPoint = mkOption {
            type = types.str;
            description = ''
              Mount point path within the WSL instance.
              This will be created as a directory if it doesn't exist.
            '';
            example = "/mnt/data";
          };

          fsType = mkOption {
            type = types.str;
            default = "ext4";
            description = ''
              Filesystem type for the mount.
              Common options: ext4, btrfs, xfs, ntfs
            '';
          };

          options = mkOption {
            type = types.listOf types.str;
            default = [ "defaults" ];
            description = ''
              Mount options to apply.
            '';
          };
        };
      });
      default = [];
      description = ''
        List of Windows disks to bare mount for use within WSL.

        These disks must be unmounted in Windows and will be exclusively
        available to WSL while mounted. The generated PowerShell script
        must be executed with Administrator privileges before starting WSL.
      '';
    };

    generateScript = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether to generate the Windows-side PowerShell mount script.
        The script will be placed in /etc/nixos-wsl/bare-mount.ps1 and
        copied to the Windows user profile on activation.
      '';
    };

    validateOnBoot = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether to validate that configured disks are mounted at boot.
        This helps catch configuration issues early.
      '';
    };

    autoInstallTask = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Whether to automatically attempt to install the Windows Task Scheduler task
        on activation. This requires running a PowerShell command as Administrator
        and will prompt for UAC elevation. Set to true for fully automated setup.
      '';
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.mounts != [];
        message = "wsl.bareMounts.enable is true but no mounts are configured";
      }
    ];

    # Create mount points and systemd mount units
    systemd.mounts = map (mount: {
      what = "/dev/disk/by-uuid/${mount.diskUuid}";
      where = mount.mountPoint;
      type = mount.fsType;
      options = concatStringsSep "," mount.options;
      wantedBy = [ "multi-user.target" ];
    }) cfg.mounts;

    systemd.tmpfiles.rules = map (mount:
      "d ${mount.mountPoint} 0755 root root -"
    ) cfg.mounts;

    # Generate the PowerShell script
    environment.etc."nixos-wsl/bare-mount.ps1" = mkIf cfg.generateScript {
      text = generateMountScript cfg.mounts;
      mode = "0644";
    };

    # Generate the Task Scheduler XML
    environment.etc."nixos-wsl/bare-mount-task.xml" = mkIf cfg.generateScript {
      text = generateTaskXml;
      mode = "0644";
    };

    # Generate the installer script
    environment.etc."nixos-wsl/install-bare-mount-task.ps1" = mkIf cfg.generateScript {
      text = generateInstallerScript;
      mode = "0644";
    };

    # Validation service
    systemd.services.validate-wsl-bare-mounts = mkIf cfg.validateOnBoot validationService;

    # Copy script to Windows user profile on activation
    system.activationScripts.wsl-bare-mount-script = mkIf cfg.generateScript ''
      # Get Windows username via cmd.exe (more reliable than whoami in WSL)
      WINDOWS_USER=$(${pkgs.coreutils}/bin/cmd.exe /c "echo %USERNAME%" 2>/dev/null | ${pkgs.coreutils}/bin/tr -d '\r\n' || echo "")
      
      # Fallback to checking actual directories if cmd.exe fails
      if [ -z "$WINDOWS_USER" ]; then
        # Look for a user directory that exists and isn't Default/Public/etc
        for dir in /mnt/c/Users/*; do
          basename_dir=$(basename "$dir")
          if [ -d "$dir" ] && [ "$basename_dir" != "Default" ] && [ "$basename_dir" != "Public" ] && [ "$basename_dir" != "All Users" ] && [ "$basename_dir" != "Default User" ] && [ "$basename_dir" != "WsiAccount" ]; then
            WINDOWS_USER="$basename_dir"
            break
          fi
        done
      fi
      
      if [ -z "$WINDOWS_USER" ]; then
        echo "ERROR: Could not determine Windows username"
        exit 1
      fi
      
      WINDOWS_HOME="/mnt/c/Users/$WINDOWS_USER"
      WSL_DIR="$WINDOWS_HOME/.nixos-wsl"

      if [ -d "$WINDOWS_HOME" ]; then
        echo "Installing WSL bare mount scripts to Windows profile for user: $WINDOWS_USER"
        mkdir -p "$WSL_DIR"

        # Copy the mount script
        cp /etc/nixos-wsl/bare-mount.ps1 "$WSL_DIR/bare-mount.ps1" 2>/dev/null || true

        # Copy the Task Scheduler XML
        cp /etc/nixos-wsl/bare-mount-task.xml "$WSL_DIR/bare-mount-task.xml" 2>/dev/null || true

        # Copy the installer script
        cp /etc/nixos-wsl/install-bare-mount-task.ps1 "$WSL_DIR/install-bare-mount-task.ps1" 2>/dev/null || true

        # Create a simple batch file wrapper for easier execution
        cat > "$WSL_DIR/bare-mount.bat" <<'EOF'
    @echo off
    powershell.exe -ExecutionPolicy Bypass -File "%~dp0bare-mount.ps1"
    pause
    EOF

        # Create installer batch file
        cat > "$WSL_DIR/install-task.bat" <<'EOF'
    @echo off
    echo This script will install a scheduled task to automatically mount bare disks
    echo You must run this as Administrator
    echo.
    pause
    powershell.exe -ExecutionPolicy Bypass -File "%~dp0install-bare-mount-task.ps1"
    pause
    EOF

        echo "Mount scripts installed to: $WSL_DIR"
        echo ""
        echo "=== NEXT STEPS ==="
        echo "1. For one-time mount, run as Administrator:"
        echo "   $WSL_DIR\\bare-mount.ps1"
        echo ""
        echo "2. For automatic mounting on login, run as Administrator:"
        echo "   $WSL_DIR\\install-bare-mount-task.ps1"
        echo ""
        echo "This will create a scheduled task that runs at user logon."
        
        ${optionalString cfg.autoInstallTask ''
          echo ""
          echo "=== AUTO-INSTALLING TASK SCHEDULER ==="
          echo "Attempting to install the scheduled task automatically..."
          echo "This will prompt for Administrator privileges..."
          
          # Try to auto-install the task (will trigger UAC prompt)
          powershell.exe -Command "Start-Process powershell -ArgumentList '-ExecutionPolicy','Bypass','-File','$WSL_DIR\\install-bare-mount-task.ps1' -Verb RunAs -Wait" 2>/dev/null || {
            echo "WARNING: Could not auto-install task. Please run manually:"
            echo "  $WSL_DIR\\install-bare-mount-task.ps1"
          }
        ''}
      else
        echo "Warning: Could not find Windows home directory at $WINDOWS_HOME"
      fi
    '';

    # Documentation
    environment.etc."nixos-wsl/bare-mount-readme.txt" = mkIf cfg.generateScript {
      text = ''
        WSL Bare Mount Configuration
        =============================

        This NixOS system is configured to use bare-mounted Windows disks.
        These disks must be mounted from Windows BEFORE starting WSL.

        Configured mounts:
        ${concatMapStringsSep "\n" (mount:
          "  - ${mount.diskUuid} -> ${mount.mountPoint} (${mount.fsType})"
        ) cfg.mounts}

        Automation Setup:
        -----------------
        The following scripts have been installed to %USERPROFILE%\.nixos-wsl\:

        1. bare-mount.ps1 - Main mount script (run manually as Admin)
        2. bare-mount-task.xml - Task Scheduler configuration
        3. install-bare-mount-task.ps1 - Automatic task installer
        4. bare-mount.bat - Batch wrapper for easy execution
        5. install-task.bat - Batch wrapper for task installation

        Quick Setup:
        ------------
        For automatic mounting on every Windows login:
        1. Run as Administrator: %USERPROFILE%\.nixos-wsl\install-bare-mount-task.ps1
        2. The task will be installed and tested automatically
        3. Disks will mount before WSL starts on each login

        Manual Mounting:
        ----------------
        Run in elevated PowerShell or Command Prompt:
        %USERPROFILE%\.nixos-wsl\bare-mount.ps1

        Task Management:
        ----------------
        - View/Edit task: Open Task Scheduler (taskschd.msc)
        - Task name: WSL-BareMountDisks
        - Task location: Task Scheduler Library\WSL
        - To uninstall: Unregister-ScheduledTask -TaskName "WSL-BareMountDisks"

        Troubleshooting:
        ----------------
        - Ensure the disk UUIDs match your Linux filesystem UUIDs (not Windows disk IDs)
        - The disks must not be in use by Windows (unmount/eject first)
        - WSL must have permission to access raw disk devices
        - Check Event Viewer for WSL-related errors
        - Run 'lsblk -o NAME,UUID' in WSL to verify disk UUIDs

        For more information, see:
        https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk
      '';
    };
  };
}